import type { Content } from "../types";

/**
 * Minimal valid Content for Simulation Engine tests: two Classes, one Stage with
 * tiny Waves, and two Equipment Bases. Passes `validateContent` only with
 * `{ fixture: true }`, which relaxes full-game cardinality (12 Equipment Bases,
 * three Stages).
 */
export const fixtureContent: Content = {
  xpThresholds: [0, 100, 250, 450, 650, 850],
  statuses: [
    {
      id: "stun",
      name: "Stun",
      kind: "stun",
      durationMs: 1200,
    },
    {
      id: "braced",
      name: "Braced",
      kind: "buff",
      durationMs: 5000,
      modifiers: { flat: { armor: 50 } },
    },
    {
      id: "warded",
      name: "Warded",
      kind: "buff",
      durationMs: 6000,
      modifiers: { flat: { elementalResistance: 20 } },
    },
  ],
  abilities: [
    {
      id: "knight-basic",
      name: "Steel Cut",
      classId: "knight",
      slot: "basic",
      targeting: { kind: "closest-opponent" },
      effects: [{ kind: "damage", channel: "physical", coefficient: 1 }],
      windUpMs: 350,
      recoveryMs: 650,
      cooldownMs: 0,
    },
    {
      id: "k-shield-brace",
      name: "Shield Brace",
      classId: "knight",
      slot: "core",
      targeting: { kind: "self" },
      effects: [{ kind: "apply-status", statusId: "braced" }],
      windUpMs: 100,
      recoveryMs: 400,
      cooldownMs: 9000,
      validWhile: "status-absent",
    },
    {
      id: "k-sweep",
      name: "Sweeping Arc",
      classId: "knight",
      slot: "core",
      targeting: { kind: "all-opponents" },
      effects: [{ kind: "damage", channel: "physical", coefficient: 0.7 }],
      windUpMs: 500,
      recoveryMs: 700,
      cooldownMs: 6000,
    },
    {
      id: "k-rally",
      name: "Rallying Guard",
      classId: "knight",
      slot: "core",
      targeting: { kind: "party" },
      effects: [{ kind: "apply-status", statusId: "warded" }],
      windUpMs: 300,
      recoveryMs: 500,
      cooldownMs: 12000,
      validWhile: "status-absent",
    },
    {
      id: "k-pommel",
      name: "Pommel Break",
      classId: "knight",
      slot: "core",
      targeting: { kind: "closest-opponent" },
      effects: [
        { kind: "damage", channel: "physical", coefficient: 0.9 },
        { kind: "apply-status", statusId: "stun", stunMs: 1200 },
      ],
      windUpMs: 250,
      recoveryMs: 650,
      cooldownMs: 9000,
    },
    {
      id: "k-hold-line",
      name: "Hold the Line",
      classId: "knight",
      slot: "talent",
      targeting: { kind: "self" },
      effects: [{ kind: "apply-status", statusId: "braced" }],
      windUpMs: 200,
      recoveryMs: 500,
      cooldownMs: 15000,
    },
    {
      id: "k-falling-star",
      name: "Falling Star",
      classId: "knight",
      slot: "talent",
      targeting: { kind: "all-opponents" },
      effects: [{ kind: "damage", channel: "physical", coefficient: 1.5 }],
      windUpMs: 700,
      recoveryMs: 800,
      cooldownMs: 12000,
    },
    {
      id: "wizard-basic",
      name: "Arc Spark",
      classId: "wizard",
      slot: "basic",
      targeting: { kind: "closest-opponent" },
      effects: [{ kind: "damage", channel: "elemental", element: "lightning", coefficient: 1 }],
      windUpMs: 450,
      recoveryMs: 750,
      cooldownMs: 0,
    },
    {
      id: "w-cinder",
      name: "Cinder Bloom",
      classId: "wizard",
      slot: "core",
      targeting: { kind: "all-opponents" },
      effects: [{ kind: "damage", channel: "elemental", element: "fire", coefficient: 0.8 }],
      windUpMs: 600,
      recoveryMs: 700,
      cooldownMs: 7000,
    },
    {
      id: "w-frost",
      name: "Frost Lance",
      classId: "wizard",
      slot: "core",
      targeting: { kind: "closest-opponent" },
      effects: [{ kind: "damage", channel: "elemental", element: "frost", coefficient: 1.8 }],
      windUpMs: 800,
      recoveryMs: 600,
      cooldownMs: 8000,
    },
    {
      id: "w-prism",
      name: "Prism Ward",
      classId: "wizard",
      slot: "core",
      targeting: { kind: "party" },
      effects: [{ kind: "apply-status", statusId: "warded" }],
      windUpMs: 300,
      recoveryMs: 500,
      cooldownMs: 12000,
      validWhile: "status-absent",
    },
    {
      id: "w-thunder",
      name: "Thunder Ring",
      classId: "wizard",
      slot: "core",
      targeting: { kind: "all-opponents" },
      effects: [
        { kind: "damage", channel: "elemental", element: "lightning", coefficient: 0.6 },
        { kind: "apply-status", statusId: "stun", stunMs: 1000 },
      ],
      windUpMs: 500,
      recoveryMs: 800,
      cooldownMs: 11000,
    },
    {
      id: "w-starfall",
      name: "Starfall",
      classId: "wizard",
      slot: "talent",
      targeting: { kind: "all-opponents" },
      effects: [{ kind: "damage", channel: "elemental", element: "fire", coefficient: 1.6 }],
      windUpMs: 900,
      recoveryMs: 800,
      cooldownMs: 14000,
    },
    {
      id: "w-shelter",
      name: "Prismatic Shelter",
      classId: "wizard",
      slot: "talent",
      targeting: { kind: "party" },
      effects: [{ kind: "apply-status", statusId: "warded" }],
      windUpMs: 400,
      recoveryMs: 600,
      cooldownMs: 15000,
    },
    {
      id: "grunt-attack",
      name: "Claw",
      classId: "knight",
      slot: "basic",
      targeting: { kind: "closest-opponent" },
      effects: [{ kind: "damage", channel: "physical", coefficient: 1 }],
      windUpMs: 400,
      recoveryMs: 600,
      cooldownMs: 0,
    },
    {
      id: "boss-smash",
      name: "Boss Smash",
      classId: "knight",
      slot: "core",
      targeting: { kind: "closest-opponent" },
      effects: [{ kind: "damage", channel: "physical", coefficient: 1.2 }],
      windUpMs: 600,
      recoveryMs: 800,
      cooldownMs: 5000,
    },
    {
      id: "priest-basic",
      name: "Light Tap",
      classId: "priest",
      slot: "basic",
      targeting: { kind: "closest-opponent" },
      effects: [{ kind: "damage", channel: "elemental", element: "light", coefficient: 1 }],
      windUpMs: 400,
      recoveryMs: 600,
      cooldownMs: 0,
    },
    {
      id: "p-moonwell",
      name: "Moonwell",
      classId: "priest",
      slot: "core",
      targeting: { kind: "lowest-health-ally" },
      effects: [{ kind: "heal", coefficient: 0.8 }],
      windUpMs: 300,
      recoveryMs: 500,
      cooldownMs: 5000,
      validWhile: "any-ally-missing-health",
    },
    {
      id: "p-resurgence",
      name: "Resurgence",
      classId: "priest",
      slot: "core",
      targeting: { kind: "first-knocked-out-ally" },
      effects: [{ kind: "revive", coefficient: 0.5 }],
      windUpMs: 500,
      recoveryMs: 700,
      cooldownMs: 12000,
    },
    {
      id: "p-ward",
      name: "Ward",
      classId: "priest",
      slot: "core",
      targeting: { kind: "self" },
      effects: [{ kind: "apply-status", statusId: "warded" }],
      windUpMs: 200,
      recoveryMs: 400,
      cooldownMs: 8000,
      validWhile: "status-absent",
    },
    {
      id: "p-smite",
      name: "Smite",
      classId: "priest",
      slot: "core",
      targeting: { kind: "closest-opponent" },
      effects: [{ kind: "damage", channel: "elemental", element: "light", coefficient: 1.4 }],
      windUpMs: 450,
      recoveryMs: 550,
      cooldownMs: 6000,
    },
    {
      id: "p-halo",
      name: "Halo",
      classId: "priest",
      slot: "talent",
      targeting: { kind: "party" },
      effects: [{ kind: "apply-status", statusId: "warded" }],
      windUpMs: 350,
      recoveryMs: 500,
      cooldownMs: 14000,
    },
    {
      id: "p-benediction",
      name: "Benediction",
      classId: "priest",
      slot: "talent",
      targeting: { kind: "lowest-health-ally" },
      effects: [{ kind: "heal", coefficient: 1.2 }],
      windUpMs: 400,
      recoveryMs: 600,
      cooldownMs: 15000,
      validWhile: "any-ally-missing-health",
    },
    {
      id: "stunner-bash",
      name: "Stunning Bash",
      classId: "knight",
      slot: "core",
      targeting: { kind: "closest-opponent" },
      effects: [
        { kind: "damage", channel: "physical", coefficient: 0.5 },
        { kind: "apply-status", statusId: "stun", stunMs: 1200 },
      ],
      windUpMs: 300,
      recoveryMs: 500,
      cooldownMs: 4000,
    },
  ],
  classes: [
    {
      id: "knight",
      name: "Knight",
      base: {
        maxHealth: 180,
        physical: 14,
        elemental: 4,
        armor: 30,
        elementalResistance: 12,
      },
      basicAbilityId: "knight-basic",
      coreAbilityIds: ["k-shield-brace", "k-sweep", "k-rally", "k-pommel"],
      defaultLoadout: ["k-shield-brace", "k-rally", "k-sweep"],
      talents: {
        statRow: [
          {
            id: "k-fortitude",
            name: "Fortitude",
            perRank: { percent: { maxHealth: 0.06 } },
            maxRanks: 5,
          },
          {
            id: "k-swordcraft",
            name: "Swordcraft",
            perRank: { percent: { physicalPower: 0.05 } },
            maxRanks: 5,
          },
        ],
        abilityRow: ["k-hold-line", "k-falling-star"],
      },
    },
    {
      id: "wizard",
      name: "Wizard",
      base: {
        maxHealth: 100,
        physical: 4,
        elemental: 16,
        armor: 10,
        elementalResistance: 24,
      },
      basicAbilityId: "wizard-basic",
      coreAbilityIds: ["w-cinder", "w-frost", "w-prism", "w-thunder"],
      defaultLoadout: ["w-prism", "w-frost", "w-cinder"],
      talents: {
        statRow: [
          {
            id: "w-elemental-practice",
            name: "Elemental Practice",
            perRank: { percent: { elementalPower: 0.05 } },
            maxRanks: 5,
          },
          {
            id: "w-warding-lore",
            name: "Warding Lore",
            perRank: { flat: { elementalResistance: 4 } },
            maxRanks: 5,
          },
        ],
        abilityRow: ["w-starfall", "w-shelter"],
      },
    },
    {
      id: "priest",
      name: "Priest",
      base: {
        maxHealth: 110,
        physical: 5,
        elemental: 14,
        armor: 15,
        elementalResistance: 20,
      },
      basicAbilityId: "priest-basic",
      coreAbilityIds: ["p-moonwell", "p-resurgence", "p-ward", "p-smite"],
      defaultLoadout: ["p-moonwell", "p-resurgence", "p-smite"],
      talents: {
        statRow: [
          {
            id: "p-devotion",
            name: "Devotion",
            perRank: { percent: { maxHealth: 0.05 } },
            maxRanks: 5,
          },
          {
            id: "p-blessing",
            name: "Blessing",
            perRank: { percent: { elementalPower: 0.04 } },
            maxRanks: 5,
          },
        ],
        abilityRow: ["p-halo", "p-benediction"],
      },
    },
  ],
  opponents: [
    {
      id: "fixture-grunt",
      name: "Fixture Grunt",
      family: "test",
      boss: false,
      base: { maxHealth: 40, physical: 8, elemental: 0, armor: 5, elementalResistance: 5 },
      abilityIds: ["grunt-attack"],
      xpAward: 20,
      spriteKey: "fixture-grunt",
    },
    {
      id: "fixture-boss",
      name: "Fixture Boss",
      family: "test",
      boss: true,
      base: { maxHealth: 200, physical: 12, elemental: 0, armor: 10, elementalResistance: 10 },
      abilityIds: ["boss-smash"],
      xpAward: 60,
      spriteKey: "fixture-boss",
    },
    {
      id: "fixture-stunner",
      name: "Fixture Stunner",
      family: "test",
      boss: false,
      base: { maxHealth: 50, physical: 6, elemental: 0, armor: 3, elementalResistance: 3 },
      abilityIds: ["stunner-bash"],
      xpAward: 15,
      spriteKey: "fixture-stunner",
    },
  ],
  stages: [
    {
      id: 1,
      name: "Fixture Stage",
      waves: [{ opponents: ["fixture-grunt"] }, { opponents: ["fixture-grunt"] }],
      boss: { opponents: ["fixture-boss"] },
      rarityOdds: [55, 35, 9, 1],
      backdropKey: "fixture-meadow",
    },
  ],
  equipmentBases: [
    {
      id: "fixture-blade",
      name: "Fixture Blade",
      slot: "weapon",
      tier: 1,
      weaponClass: "knight",
      guaranteed: { flat: { physical: 2 } },
      iconKey: "fixture-blade",
    },
    {
      id: "fixture-focus",
      name: "Fixture Focus",
      slot: "weapon",
      tier: 1,
      weaponClass: "wizard",
      guaranteed: { flat: { elemental: 2 } },
      iconKey: "fixture-focus",
    },
    {
      id: "fixture-relic",
      name: "Fixture Relic",
      slot: "weapon",
      tier: 1,
      weaponClass: "priest",
      guaranteed: { flat: { elemental: 2 } },
      iconKey: "fixture-relic",
    },
    {
      id: "fixture-bow",
      name: "Fixture Bow",
      slot: "weapon",
      tier: 1,
      weaponClass: "hunter",
      guaranteed: { flat: { physical: 2 } },
      iconKey: "fixture-bow",
    },
    {
      id: "fixture-armor",
      name: "Fixture Armor",
      slot: "armor",
      tier: 1,
      guaranteed: { flat: { armor: 4 } },
      iconKey: "fixture-armor",
    },
    {
      id: "fixture-charm",
      name: "Fixture Charm",
      slot: "charm",
      tier: 1,
      guaranteed: { flat: { maxHealth: 8 } },
      iconKey: "fixture-charm",
    },
    {
      id: "fixture-blade-ii",
      name: "Fixture Blade II",
      slot: "weapon",
      tier: 2,
      weaponClass: "knight",
      guaranteed: { flat: { physical: 5 } },
      iconKey: "fixture-blade-ii",
    },
    {
      id: "fixture-focus-ii",
      name: "Fixture Focus II",
      slot: "weapon",
      tier: 2,
      weaponClass: "wizard",
      guaranteed: { flat: { elemental: 5 } },
      iconKey: "fixture-focus-ii",
    },
    {
      id: "fixture-relic-ii",
      name: "Fixture Relic II",
      slot: "weapon",
      tier: 2,
      weaponClass: "priest",
      guaranteed: { flat: { elemental: 5 } },
      iconKey: "fixture-relic-ii",
    },
    {
      id: "fixture-bow-ii",
      name: "Fixture Bow II",
      slot: "weapon",
      tier: 2,
      weaponClass: "hunter",
      guaranteed: { flat: { physical: 5 } },
      iconKey: "fixture-bow-ii",
    },
    {
      id: "fixture-armor-ii",
      name: "Fixture Armor II",
      slot: "armor",
      tier: 2,
      guaranteed: { flat: { armor: 9 } },
      iconKey: "fixture-armor-ii",
    },
    {
      id: "fixture-charm-ii",
      name: "Fixture Charm II",
      slot: "charm",
      tier: 2,
      guaranteed: { flat: { maxHealth: 18 } },
      iconKey: "fixture-charm-ii",
    },
  ],
  affixBands: [
    { id: "flat-physical", tier1: [1, 3], tier2: [2, 5] },
    { id: "percent-physical-power", tier1: [0.02, 0.04], tier2: [0.03, 0.06] },
    { id: "flat-elemental", tier1: [1, 3], tier2: [2, 5] },
    { id: "percent-elemental-power", tier1: [0.02, 0.04], tier2: [0.03, 0.06] },
    { id: "flat-max-health", tier1: [5, 10], tier2: [8, 15] },
    { id: "percent-max-health", tier1: [0.02, 0.04], tier2: [0.03, 0.06] },
    { id: "flat-armor", tier1: [2, 4], tier2: [3, 6] },
    { id: "flat-elemental-resistance", tier1: [2, 4], tier2: [3, 6] },
  ],
};
