"""Parse and emit committed text-grid icon sources (#126 decision 2)."""

from __future__ import annotations

import pathlib
import re
from dataclasses import dataclass

from .palette import PALETTE, PALETTE_NAMES, Swatch

GENERATED_HEADER = "# generated by pipeline/icons — do not hand-edit"


@dataclass(frozen=True)
class TextSource:
    source_key: str
    palette_subset: tuple[str, ...]
    legend: dict[str, str | None]
    rows: tuple[str, ...]

    def palette_subset_set(self) -> frozenset[str]:
        return frozenset(self.palette_subset)


def _parse_subset_line(line: str) -> tuple[str, ...]:
    _, _, rest = line.partition(":")
    names = [part.strip() for part in rest.split(",") if part.strip()]
    if not names:
        raise ValueError("palette_subset must name at least one moonberry-16 ref")
    unknown = [n for n in names if n not in PALETTE_NAMES]
    if unknown:
        raise ValueError(f"palette_subset names unknown colours: {unknown}")
    return tuple(names)


def parse_text(path: pathlib.Path) -> TextSource:
    text = path.read_text()
    lines = text.splitlines()
    source_key = ""
    palette_subset: tuple[str, ...] = ()
    legend: dict[str, str | None] = {}
    rows: list[str] = []
    section: str | None = None
    subset_set: frozenset[str] = frozenset()

    for raw in lines:
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        if line == "legend":
            section = "legend"
            continue
        if line == "grid":
            section = "grid"
            continue
        if line.startswith("source_key:"):
            source_key = line.split(":", 1)[1].strip()
            continue
        if line.startswith("palette_subset:"):
            palette_subset = _parse_subset_line(line)
            subset_set = frozenset(palette_subset)
            continue
        if section == "legend":
            if " " not in line:
                raise ValueError(f"legend line must be '<char> <name>|.': {line!r}")
            ch, name = line.split(None, 1)
            if len(ch) != 1:
                raise ValueError(f"legend key must be one character: {ch!r}")
            if name == ".":
                legend[ch] = None
            else:
                if name not in PALETTE_NAMES:
                    raise ValueError(f"legend names off-palette colour {name!r}")
                if subset_set and name not in subset_set:
                    raise ValueError(
                        f"legend colour {name!r} not in declared palette_subset"
                    )
                legend[ch] = name
            continue
        if section == "grid":
            if not re.fullmatch(r"[.A-Za-z0-9]+", line):
                raise ValueError(f"grid row has illegal characters: {line!r}")
            for ch in line:
                if ch not in legend:
                    raise ValueError(f"grid uses undefined legend char {ch!r}")
            rows.append(line)

    if not source_key:
        raise ValueError(f"{path}: missing source_key")
    if not palette_subset:
        raise ValueError(f"{path}: missing palette_subset")
    if not legend:
        raise ValueError(f"{path}: missing legend")
    if not rows:
        raise ValueError(f"{path}: missing grid rows")
    width = len(rows[0])
    if any(len(row) != width for row in rows):
        raise ValueError(f"{path}: ragged grid")

    return TextSource(source_key, palette_subset, legend, tuple(rows))


def write_text(path: pathlib.Path, source: TextSource) -> None:
    lines = [
        GENERATED_HEADER,
        f"source_key: {source.source_key}",
        f"palette_subset: {', '.join(source.palette_subset)}",
        "",
        "legend",
    ]
    for ch in sorted(source.legend.keys()):
        name = source.legend[ch]
        lines.append(f"{ch} ." if name is None else f"{ch} {name}")
    lines.extend(["", "grid", *source.rows, ""])
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines))


def cells_from_source(source: TextSource) -> list[list[Swatch | None]]:
    cells: list[list[Swatch | None]] = []
    for row in source.rows:
        out_row: list[Swatch | None] = []
        for ch in row:
            name = source.legend[ch]
            out_row.append(None if name is None else PALETTE[name])
        cells.append(out_row)
    return cells


def cells_to_source(
    source_key: str,
    palette_subset: tuple[str, ...],
    cells: list[list[Swatch | None]],
) -> TextSource:
    subset = frozenset(palette_subset)
    legend: dict[str, str | None] = {".": None}
    char_for: dict[str | None, str] = {None: "."}
    next_ord = ord("A")

    def char_for_name(name: str | None) -> str:
        if name in char_for:
            return char_for[name]
        nonlocal next_ord
        while True:
            ch = chr(next_ord)
            next_ord += 1
            if ch not in legend and ch != ".":
                break
        legend[ch] = name
        char_for[name] = ch
        return ch

    rows: list[str] = []
    for row in cells:
        line = ""
        for cell in row:
            if cell is None:
                line += "."
                continue
            if cell.name not in subset:
                raise ValueError(
                    f"cell colour {cell.name!r} outside family palette_subset"
                )
            line += char_for_name(cell.name)
        rows.append(line)

    return TextSource(source_key, palette_subset, legend, tuple(rows))
