"""Parse and emit committed text-grid icon sources (#126 decision 2)."""

from __future__ import annotations

import pathlib
import re
from dataclasses import dataclass
from typing import Literal

from .palette import (
    DEFAULT_SOURCE_PALETTE_ID,
    NAMED_PALETTE_COLOR_MODE,
    SOURCE_LOCAL_COLOR_MODE,
    RuntimePalette,
    Swatch,
    format_opaque_rgb,
    load_runtime_palette,
    parse_opaque_rgb,
    swatch_for_local_rgb,
    validate_source_local_outline,
)

GENERATED_HEADER = "# generated by pipeline/icons — do not hand-edit"

ColorMode = Literal["named-palette", "source-local"]


@dataclass(frozen=True)
class TextSource:
    source_key: str
    rows: tuple[str, ...]
    color_mode: ColorMode = NAMED_PALETTE_COLOR_MODE
    palette_id: str = DEFAULT_SOURCE_PALETTE_ID
    palette_subset: tuple[str, ...] = ()
    legend: dict[str, str | None] | None = None
    local_legend: dict[str, tuple[int, int, int] | None] | None = None
    outline_rgb: tuple[int, int, int] | None = None

    def palette_subset_set(self) -> frozenset[str]:
        return frozenset(self.palette_subset)

    def runtime_palette(self) -> RuntimePalette:
        return load_runtime_palette(self.palette_id)


def _parse_subset_line(line: str, palette_names: frozenset[str]) -> tuple[str, ...]:
    _, _, rest = line.partition(":")
    names = [part.strip() for part in rest.split(",") if part.strip()]
    if not names:
        raise ValueError("palette_subset must name at least one palette ref")
    unknown = [n for n in names if n not in palette_names]
    if unknown:
        raise ValueError(f"palette_subset names unknown colours: {unknown}")
    return tuple(names)


def _parse_color_mode(line: str) -> ColorMode:
    _, _, rest = line.partition(":")
    mode = rest.strip()
    if mode == SOURCE_LOCAL_COLOR_MODE:
        return SOURCE_LOCAL_COLOR_MODE
    if mode == NAMED_PALETTE_COLOR_MODE:
        return NAMED_PALETTE_COLOR_MODE
    raise ValueError(f"unknown color_mode {mode!r}")


def parse_text(path: pathlib.Path) -> TextSource:
    text = path.read_text()
    lines = text.splitlines()
    source_key = ""
    color_mode: ColorMode = NAMED_PALETTE_COLOR_MODE
    palette_id = DEFAULT_SOURCE_PALETTE_ID
    palette_subset: tuple[str, ...] = ()
    outline_rgb: tuple[int, int, int] | None = None
    named_legend: dict[str, str | None] = {}
    local_legend: dict[str, tuple[int, int, int] | None] = {}
    rows: list[str] = []
    section: str | None = None
    subset_set: frozenset[str] = frozenset()
    palette_names = load_runtime_palette(palette_id).names
    saw_palette_line = False
    saw_subset_line = False
    saw_color_mode_line = False
    rgb_values_seen: set[tuple[int, int, int]] = set()

    for raw in lines:
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        if line == "legend":
            section = "legend"
            continue
        if line == "grid":
            section = "grid"
            continue
        if line.startswith("source_key:"):
            source_key = line.split(":", 1)[1].strip()
            continue
        if line.startswith("color_mode:"):
            saw_color_mode_line = True
            color_mode = _parse_color_mode(line)
            continue
        if line.startswith("outline:"):
            _, _, rest = line.partition(":")
            outline_rgb = parse_opaque_rgb(rest.strip(), context=f"{path}: outline")
            validate_source_local_outline(outline_rgb)
            continue
        if line.startswith("palette:"):
            if color_mode == SOURCE_LOCAL_COLOR_MODE:
                raise ValueError(f"{path}: palette line forbidden in source-local mode")
            declared = line.split(":", 1)[1].strip()
            if not declared:
                raise ValueError(f"{path}: empty palette id")
            saw_palette_line = True
            palette_id = declared
            palette_names = load_runtime_palette(palette_id).names
            continue
        if line.startswith("palette_subset:"):
            if color_mode == SOURCE_LOCAL_COLOR_MODE:
                raise ValueError(
                    f"{path}: palette_subset forbidden in source-local mode"
                )
            saw_subset_line = True
            palette_subset = _parse_subset_line(line, palette_names)
            subset_set = frozenset(palette_subset)
            continue
        if section == "legend":
            if " " not in line:
                raise ValueError(f"legend line must be '<char> <name>|.': {line!r}")
            ch, name = line.split(None, 1)
            if len(ch) != 1:
                raise ValueError(f"legend key must be one character: {ch!r}")
            if color_mode == SOURCE_LOCAL_COLOR_MODE:
                if ch in local_legend:
                    raise ValueError(f"{path}: duplicate legend char {ch!r}")
                if name == ".":
                    local_legend[ch] = None
                    continue
                rgb = parse_opaque_rgb(name, context=f"{path}: legend {ch!r}")
                if rgb in rgb_values_seen:
                    raise ValueError(
                        f"{path}: duplicate legend rgb {format_opaque_rgb(rgb)!r}"
                    )
                rgb_values_seen.add(rgb)
                local_legend[ch] = rgb
            else:
                if ch in named_legend:
                    raise ValueError(f"{path}: duplicate legend char {ch!r}")
                if name == ".":
                    named_legend[ch] = None
                else:
                    if name not in palette_names:
                        raise ValueError(f"legend names off-palette colour {name!r}")
                    if subset_set and name not in subset_set:
                        raise ValueError(
                            f"legend colour {name!r} not in declared palette_subset"
                        )
                    named_legend[ch] = name
            continue
        if section == "grid":
            if not re.fullmatch(r"[.A-Za-z0-9]+", line):
                raise ValueError(f"grid row has illegal characters: {line!r}")
            active_legend = (
                local_legend if color_mode == SOURCE_LOCAL_COLOR_MODE else named_legend
            )
            for ch in line:
                if ch not in active_legend:
                    raise ValueError(f"grid uses undefined legend char {ch!r}")
            rows.append(line)

    if not source_key:
        raise ValueError(f"{path}: missing source_key")
    if color_mode == SOURCE_LOCAL_COLOR_MODE:
        if saw_palette_line or saw_subset_line:
            raise ValueError(f"{path}: named-palette fields forbidden in source-local mode")
        if not saw_color_mode_line:
            raise ValueError(f"{path}: source-local sources require color_mode line")
        if outline_rgb is None:
            raise ValueError(f"{path}: source-local sources require outline line")
        if not local_legend:
            raise ValueError(f"{path}: missing legend")
        if not rows:
            raise ValueError(f"{path}: missing grid rows")
        width = len(rows[0])
        if any(len(row) != width for row in rows):
            raise ValueError(f"{path}: ragged grid")
        return TextSource(
            source_key,
            tuple(rows),
            color_mode=SOURCE_LOCAL_COLOR_MODE,
            local_legend=local_legend,
            outline_rgb=outline_rgb,
        )

    if saw_color_mode_line and color_mode != NAMED_PALETTE_COLOR_MODE:
        raise ValueError(f"{path}: invalid color_mode for named palette source")
    if not palette_subset:
        raise ValueError(f"{path}: missing palette_subset")
    if not named_legend:
        raise ValueError(f"{path}: missing legend")
    if not rows:
        raise ValueError(f"{path}: missing grid rows")
    width = len(rows[0])
    if any(len(row) != width for row in rows):
        raise ValueError(f"{path}: ragged grid")

    return TextSource(
        source_key,
        tuple(rows),
        color_mode=NAMED_PALETTE_COLOR_MODE,
        palette_id=palette_id,
        palette_subset=palette_subset,
        legend=named_legend,
    )


def write_text(path: pathlib.Path, source: TextSource) -> None:
    lines = [GENERATED_HEADER, f"source_key: {source.source_key}"]
    if source.color_mode == SOURCE_LOCAL_COLOR_MODE:
        if source.outline_rgb is None or source.local_legend is None:
            raise ValueError("source-local TextSource missing outline or legend")
        lines.extend(
            [
                f"color_mode: {SOURCE_LOCAL_COLOR_MODE}",
                f"outline: {format_opaque_rgb(source.outline_rgb)}",
                "",
                "legend",
            ]
        )
        for ch in sorted(source.local_legend.keys()):
            rgb = source.local_legend[ch]
            lines.append(f"{ch} ." if rgb is None else f"{ch} {format_opaque_rgb(rgb)}")
    else:
        if source.legend is None:
            raise ValueError("named-palette TextSource missing legend")
        lines.extend(
            [
                f"palette: {source.palette_id}",
                f"palette_subset: {', '.join(source.palette_subset)}",
                "",
                "legend",
            ]
        )
        for ch in sorted(source.legend.keys()):
            name = source.legend[ch]
            lines.append(f"{ch} ." if name is None else f"{ch} {name}")
    lines.extend(["", "grid", *source.rows, ""])
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines))


def cells_from_source(source: TextSource) -> list[list[Swatch | None]]:
    cells: list[list[Swatch | None]] = []
    if source.color_mode == SOURCE_LOCAL_COLOR_MODE:
        if source.local_legend is None:
            raise ValueError("source-local source missing local_legend")
        for row in source.rows:
            out_row: list[Swatch | None] = []
            for ch in row:
                rgb = source.local_legend[ch]
                out_row.append(None if rgb is None else swatch_for_local_rgb(rgb))
            cells.append(out_row)
        return cells

    if source.legend is None:
        raise ValueError("named-palette source missing legend")
    swatches = source.runtime_palette().swatches
    for row in source.rows:
        out_row: list[Swatch | None] = []
        for ch in row:
            name = source.legend[ch]
            out_row.append(None if name is None else swatches[name])
        cells.append(out_row)
    return cells


def cells_to_source(
    source_key: str,
    palette_id: str,
    palette_subset: tuple[str, ...],
    cells: list[list[Swatch | None]],
) -> TextSource:
    runtime = load_runtime_palette(palette_id)
    subset = frozenset(palette_subset)
    unknown_subset = [n for n in palette_subset if n not in runtime.names]
    if unknown_subset:
        raise ValueError(
            f"palette_subset names unknown colours for {palette_id!r}: {unknown_subset}"
        )
    legend: dict[str, str | None] = {".": None}
    char_for: dict[str | None, str] = {None: "."}
    next_ord = ord("A")

    def char_for_name(name: str | None) -> str:
        if name in char_for:
            return char_for[name]
        nonlocal next_ord
        while True:
            ch = chr(next_ord)
            next_ord += 1
            if ch not in legend and ch != ".":
                break
        legend[ch] = name
        char_for[name] = ch
        return ch

    rows: list[str] = []
    for row in cells:
        line = ""
        for cell in row:
            if cell is None:
                line += "."
                continue
            if cell.name not in runtime.names:
                raise ValueError(
                    f"cell colour {cell.name!r} not in palette {palette_id!r}"
                )
            if cell.name not in subset:
                raise ValueError(
                    f"cell colour {cell.name!r} outside family palette_subset"
                )
            line += char_for_name(cell.name)
        rows.append(line)

    return TextSource(
        source_key,
        tuple(rows),
        color_mode=NAMED_PALETTE_COLOR_MODE,
        palette_id=palette_id,
        palette_subset=palette_subset,
        legend=legend,
    )


def cells_to_local_source(
    source_key: str,
    cells: list[list[tuple[int, int, int] | None]],
    *,
    outline_rgb: tuple[int, int, int] | None = None,
) -> TextSource:
    from .palette import SOURCE_LOCAL_OUTLINE_RGB

    outline = outline_rgb or SOURCE_LOCAL_OUTLINE_RGB
    validate_source_local_outline(outline)
    legend: dict[str, tuple[int, int, int] | None] = {".": None}
    char_for: dict[tuple[int, int, int] | None, str] = {None: "."}
    next_ord = ord("A")
    rgb_values_seen: set[tuple[int, int, int]] = set()

    def char_for_rgb(rgb: tuple[int, int, int] | None) -> str:
        if rgb in char_for:
            return char_for[rgb]
        if rgb is not None and rgb in rgb_values_seen:
            raise ValueError(
                f"duplicate cell rgb {format_opaque_rgb(rgb)!r} in source-local ingest"
            )
        nonlocal next_ord
        while True:
            ch = chr(next_ord)
            next_ord += 1
            if ch not in legend and ch != ".":
                break
        legend[ch] = rgb
        if rgb is not None:
            rgb_values_seen.add(rgb)
        char_for[rgb] = ch
        return ch

    rows: list[str] = []
    for row in cells:
        line = ""
        for rgb in row:
            if rgb is None:
                line += "."
                continue
            line += char_for_rgb(rgb)
        rows.append(line)

    return TextSource(
        source_key,
        tuple(rows),
        color_mode=SOURCE_LOCAL_COLOR_MODE,
        local_legend=legend,
        outline_rgb=outline,
    )
